version: '3'
services:
  app:
    build: .
    container_name: "ptn_1"
    tty: true
    volumes:
      - ./:/usr/src/app
    networks:  # <-- here
      - nginx_network

    #ports:
    #  - "8000:8000"
 
  nginx:
    image: nginx:1.13
    container_name: "ptn_nginx"
    ports:
      - 8000:80
      - 8001:81
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/home
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - app
    networks:  # <-- here
      - nginx_network


networks:  # <-- and here
  nginx_network:
    driver: bridge
