version: '3'
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
    container_name: "ptn"
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
   
